modLoader="javafml"
loaderVersion="[41,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/ItemsDontBreak/issues"

[[mods]] #mandatory
modId="itemsdontbreak"
version="${file.jarVersion}"
displayName="Items Don't Break"
logoFile="logo.png"
authors="gigaherz"
description='''
Warns of remaining item uses, and prevents using an item when it reaches 0 durability
'''
displayURL="https://github.com/gigaherz/ItemsDontBreak"

[[dependencies.itemsdontbreak]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41.0.94,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.itemsdontbreak]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
