modLoader="javafml"
loaderVersion="[28,)"
displayURL="https://github.com/gigaherz/ItemsDontBreak"
issueTrackerURL="https://github.com/gigaherz/ItemsDontBreak/issues"
#updateJSONURL="http://myurl.me/" #optional
logoFile="logo.png"
credits="Thanks for this example mod goes to Java"
authors="gigaherz"

[[mods]] #mandatory
modId="itemsdontbreak"
version="${file.jarVersion}"
displayName="Items Don't Break"
description='''
Warns of remaining item uses, and prevents using an item when it reaches 0 durability
'''

[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28.0.45,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4,1.14.0)"
    ordering="NONE"
    side="BOTH"
