modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
#issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
modId="itemsdontbreak" #mandatory
version="${version}" #mandatory
displayName="Items Don't Break" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
logoFile="logo.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="gigaherz" #optional
description='''
Warns of remaining item uses, and prevents using an item when it reaches 0 durability
'''

[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[25,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2,1.14.0)"
    ordering="NONE"
    side="BOTH"